Flowpack:
  Neos:
    Debug:
      enabled: false
      htmlOutput:
        enabled: true
      serverTimingHeader:
        enabled: false
      sql:
        # Set when a query should be considered as slow query. In ms
        slowQueryAfter: 10
      ignore:
        fusionPrototypes: []
